[build]
  # # no build needed
  # command = "npm run build"
  # not serving anything either
  publish = "dist"
  # functions build directory
  functions = ".netlify/functions"

#[[redirects]]
#  from = "/"
#  to = "/.netlify/functions/pages"
#  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/pages/:splat"
  status = 200