[build]
  # # no build needed
  # command = "npm run build"
  # # not serving anything either
  # publish = "public"
  # functions build directory
  functions = "functions-build"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/react"
  status = 200

#[[redirects]]
#  from = "/*"
#  to = "/.netlify/functions/react/:splat"
#  status = 200