[build]
  # # no build needed
  # command = "npm run build"
  # not serving anything either
  publish = "dist"
  # functions build directory
  functions = ".netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/pages"
  status = 200

[[redirects]]
  from = "/pages/*"
  to = "/.netlify/functions/pages/:splat"
  status = 200